DELETE FROM __MigrationHistory;
DROP TABLE AspNetUserRoles;
DROP TABLE AspNetUserLogins;
DROP TABLE AspNetUserClaims;
DROP TABLE AspNetRoles;
DROP TABLE AspNetUsers;
DROP TABLE AuthentificationConfig;
DROP TABLE LoginConfig;
DROP TABLE UserLoginLog;
