// <auto-generated />
namespace GTI619_Lab5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class kekekeke : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kekekeke));
        
        string IMigrationMetadata.Id
        {
            get { return "201611242137137_kekekeke"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
